#!/bin/bash

cd "$(dirname "$0")"

# Start up Google Compute Engine instances
cd terraform
terraform apply

# Create ansible hosts file
cat <<EOS >../ansible/hosts
[master]
$(terraform output -json instance_ips | jq '.[0]' | tr -d '"')

[slave]
$(terraform output -json instance_ips | jq -r '.[1:] | join("\n")' | tr -d '"')
EOS

# Create MPI hosts file
cat <<EOS >../ansible/roles/master/files/hosts
# master
$(terraform output -json instance_ips | jq '.[0]' | tr -d '"')

# slave
$(terraform output -json instance_ips | jq -r '.[1:] | join("\n")' | tr -d '"')
EOS

# Configure MPI cluster
cd ../ansible
ansible-playbook site.yml -i hosts
