- name: Install common packages
  yum:
    name: [
      'emacs',
      'mpich',
      'mpich-devel',
      'gcc-c++'
    ]
    state: installed

- name: Create the MPI user
  user: name=mpiusr comment="MPI user"

- name: Create work directory
  file:
    path: "{{ mpi_work_dir }}"
    state: directory
    owner: mpiusr
    group: mpiusr
    recurse: True

- name: Add mpi to PATH
  copy:
    src: ../files/bash_profile
    dest: "/home/mpiusr/.bash_profile"
    owner: mpiusr
    group: mpiusr
    mode: 0644

- name: Disable strict host key checking
  copy:
    src: ../files/ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
