- name: Install common packages
  yum: name={{ item }} state=installed
  with_items:
   - emacs
   - mpich
   - mpich-devel
   - gcc-c++
  become: True
  become_method: sudo

- name: Create the MPI user
  user: name=mpiusr comment="MPI user"
  become: True
  become_method: sudo

- name: Create work directory
  file:
    path: "{{ mpi_work_dir }}"
    state: directory
    owner: mpiusr
    group: mpiusr
    recurse: True
  become: True
  become_method: sudo

- name: Copy sample programs
  copy:
    src: ../files/hello.cpp
    dest: "{{ mpi_work_dir }}/hello.cpp"
    owner: mpiusr
    group: mpiusr
    mode: 0644
  become: True
  become_method: sudo
