- name: Wait for server to become reachable
  wait_for_connection:
    timeout: 300

- name: Install common packages
  yum:
    name: [
      'emacs',
      'mpich',
      'mpich-devel',
      'gcc-c++'
    ]
    state: installed
  become: True
  become_method: sudo

- name: Create the MPI user
  user: name=mpiusr comment="MPI user"
  become: True
  become_method: sudo

- name: Create work directory
  file:
    path: "{{ mpi_work_dir }}"
    state: directory
    owner: mpiusr
    group: mpiusr
    recurse: True
  become: True
  become_method: sudo

- name: Add mpi to PATH
  copy:
    src: ../files/bash_profile
    dest: "/home/mpiusr/.bash_profile"
    owner: mpiusr
    group: mpiusr
    mode: 0644
  become: True
  become_method: sudo
