- name: Generate ssh key
  shell: yes | ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

- name: Register public key
  shell: cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys

- name: Change authorized_keys mode
  file:
    path: ~/.ssh/authorized_keys
    mode: 0600

- name: Fetch public key
  fetch:
    src: ~/.ssh/id_rsa.pub
    dest: roles/slave/files/
    flat: yes

- name: Copy hosts file
  copy:
    src: ../files/hosts
    dest: "{{ mpi_work_dir }}/hosts"
    owner: mpiusr
    group: mpiusr
    mode: 0644
