- hosts: all
  tasks: 
    - name: Create Work Directory
      file:
        path: "{{ mpi_work_dir }}/hello"
        state: directory
        owner: mpiusr
        group: mpiusr
      become: True
      become_method: sudo

    - name: Copy MPI programs
      copy:
        src: ../app/hello/main.cpp
        dest: "{{ mpi_work_dir }}/hello/main.cpp"
        owner: mpiusr
        group: mpiusr
        mode: 0644
      become: True
      become_method: sudo

    - name: Compile MPI program
      shell: /usr/lib64/mpich/bin/mpic++ hello/main.cpp -o hello/main
      args:
        chdir: "{{ mpi_work_dir }}"
      become: yes
      become_user: mpiusr
