- hosts: all
  become: yes
  become_user: mpiusr
  tasks: 
    - name: Create Work Directory
      file:
        path: "{{ mpi_work_dir }}/{{ program }}"
        state: directory
        owner: mpiusr
        group: mpiusr

    - name: Copy MPI programs
      copy:
        src: "../app/{{ program }}/main.cpp"
        dest: "{{ mpi_work_dir }}/{{ program }}/main.cpp"
        owner: mpiusr
        group: mpiusr
        mode: 0644

    - name: Compile MPI program
      shell: "/usr/lib64/mpich/bin/mpic++ {{ program }}/main.cpp -o {{ program }}/main"
      args:
        chdir: "{{ mpi_work_dir }}"
