- hosts: all
  tasks: 
    - name: compile MPI program
      shell: /usr/lib64/mpich/bin/mpicc hello.c -o hello
      args:
        chdir: "{{ mpi_work_dir }}"
      become: yes
      become_user: mpiusr
