- hosts: master
  tasks: 
    - name: run MPI program
      shell: "/usr/lib64/mpich/bin/mpirun --hostfile hosts {{ mpi_work_dir }}/{{ program }}/main"
      args:
        chdir: "{{ mpi_work_dir }}"
      become: yes
      become_user: mpiusr
      register: result

    - name: show result
      debug: 
        msg: "{{ result.stdout_lines }}"
