- name: Create ssh directory
  file:
    path: ~/.ssh
    state: directory
    owner: mpiusr
    group: mpiusr
    mode: 0700
  become: yes
  become_user: mpiusr

- name: Copy public key
  copy:
    src: ../files/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    owner: mpiusr
    group: mpiusr
  become: yes
  become_user: mpiusr

- name: Register public key
  shell: cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
  become: yes
  become_user: mpiusr

- name: Change authorized_keys mode
  file:
    path: ~/.ssh/authorized_keys
    mode: 0600
  become: yes
  become_user: mpiusr
